import express, { Application } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import cookieParser from 'cookie-parser';
import { errorHandler, notFound } from './middleware/errorHandler';
import { validateLLMConfig } from './config/llm';
import { testConnection } from './db';
import { testPipelineConnection } from './db/pipeline';
import { authMiddleware } from './middleware/auth.middleware';

// Load environment variables
dotenv.config();

// Import routes
import listingRoutes from './routes/listing.routes';
import authRoutes from './routes/auth.routes';
import scrapingRoutes from './routes/scraping.routes';
import leadRoutes from './routes/lead.routes';
import followUpRoutes from './routes/followUp.routes';
import dashboardRoutes from './routes/dashboard.routes';
import pipelineRoutes from './routes/pipeline.routes';

const app: Application = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors({
  origin: process.env.CORS_ORIGIN || true,
  credentials: true,
}));

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());

// Static files for uploads
const uploadDir = process.env.UPLOAD_DIR || './uploads';
app.use('/uploads', express.static(path.join(__dirname, '..', uploadDir)));

// Static files for poster images generated by sosmed-agent
const posterBaseDir = process.env.POSTER_BASE_DIR;
if (posterBaseDir) {
  app.use('/posters', express.static(posterBaseDir));
}

// Static files for listing assets produced by the CSCORP listing agent.
// The pipeline DB stores web-relative paths (e.g. assets/listings/x.jpg) which
// live outside this project, so without this mount the frontend dev server
// answers those URLs with its SPA fallback (HTML) and every <img> fails.
const assetsBaseDir = process.env.ASSETS_BASE_DIR;
if (assetsBaseDir) {
  app.use('/assets', express.static(assetsBaseDir));
}

// Health check
app.get('/health', (req, res) => {
  res.json({
    success: true,
    message: 'FreePropAI API is running',
    timestamp: new Date().toISOString(),
  });
});

// API Routes
app.get('/api', (req, res) => {
  res.json({
    success: true,
    message: 'FreePropAI API v1.0',
    endpoints: {
      leads: '/api/leads',
      followups: '/api/followups',
      listings: '/api/listings',
      dashboard: '/api/dashboard',
      pipeline: '/api/pipeline',
    },
  });
});

// Mount routes
app.use('/api/auth', authRoutes);
app.use('/api/listings', listingRoutes);
app.use('/api/scraping', scrapingRoutes);
app.use('/api/leads', leadRoutes);
app.use('/api/followups', followUpRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/pipeline', pipelineRoutes);

const frontendDist = process.env.FRONTEND_DIST || path.join(__dirname, '..', 'public');
app.use(express.static(frontendDist));
app.get('*', (req, res, next) => {
  if (
    req.path.startsWith('/api') ||
    req.path.startsWith('/uploads') ||
    req.path.startsWith('/posters') ||
    req.path.startsWith('/health')
  ) {
    return next();
  }
  res.sendFile(path.join(frontendDist, 'index.html'), (err) => {
    if (err) next();
  });
});

// Error handling
app.use(notFound);
app.use(errorHandler);

// Start server
const startServer = async () => {
  try {
    // Test database connection
    await testConnection();

    // Test optional pipeline database connection (non-fatal)
    await testPipelineConnection();
    
    // Validate LLM configuration
    validateLLMConfig();
    
    app.listen(PORT, () => {
      console.log(`🚀 Server is running on port ${PORT}`);
      console.log(`📍 Environment: ${process.env.NODE_ENV || 'development'}`);
      console.log(`🔗 API: http://localhost:${PORT}/api`);
      console.log(`💚 Health: http://localhost:${PORT}/health`);
    });
  } catch (error) {
    console.error('Failed to start server:', error);
    process.exit(1);
  }
};

if (process.env.NODE_ENV !== 'test') {
  startServer();
}

export default app;
